### ISSUE TITLE
When the hidden talks in game, a speech bubble is shown above his head

### ISSUE THREAD

**Issue by ghost** [atomic-penguin/sm-hidden#11]
Would be nice if this was optional

**Comment by ghost** [comment]
just had a thought, is this an issue only because we're forcing the server to alltalk?

**Comment by atomic-penguin** [comment]
Yes, that is why it happens.  I would think this is a gamemode which alltalk would be ideal way to play though, would it not?

**Comment by ghost** [comment]
yer all talk is a must imo, and it is how _most_ hidden:source servers run. i think we should look into checking if the speech bubble counts as a player condition like fire, jarate, or the the mark of death, because then we can remove it.

**Comment by ghost** [comment]
it seems we can't alter the appearance of speech bubbles if the spy has an open voice channel. however there is this http://forums.alliedmods.net/showthread.php?p=1321681 plugin which blocks alltalk for spies when they are cloaked or disgused. others have suggested the cvar tf_show_voice_icons. it looks like there's little we can do from within the hidden though.

**Comment by atomic-penguin** [comment]
Could expose a cvar for tf2_hidden_alltalk, which toggles the game into one of two states:

```
# When tf2_hidden_alltalk 1(recommended setting)
sv_alltalk 1// Hidden & Iris team may talk with one another
mp_show_voice_icons 0 // Talking does not give away Hidden, nobody has speech bubble animation however.

# When tf2_hidden_alltalk 0
sv_alltalk 0 // Hidden cannot hear Iris team, or speak with them.
mp_show_voice_icons 1 // Iris team can see one another's speech bubbles.
```

**Comment by ghost** [comment]
looks good to me!

**Comment by ghost** [comment]
so are we happy with the server side fix? or do we want an admin command to do this from within the plugin?

**Comment by atomic-penguin** [comment]
I am going to have the plugin control this aspect.

Eric G. Wolfe
Senior Linux Administrator,

## IT Infrastructure Systems

Marshall University Computing Services
Drinko Library 428-K
One John Marshall Dr.
Huntington, WV 25755
Phone: 304.942.3970
Email: eric.wolfe@marshall.edu

You will be recognized and honored as a community leader.

**Comment by atomic-penguin** [comment]
This is fixed, thanks Dan
