### ISSUE TITLE
Iris could take no self-explovesive damage

### ISSUE THREAD

**Issue by ghost** [atomic-penguin/sm-hidden#16]
to prevent sollys from dying when the hidden is right in their face f.e

**Comment by atomic-penguin** [comment]
I don't feel this is game breaking. Annoying perhaps, if you are a soldier or demoman.  Depending on the loadout, the hidden player is going to have a certain close combat advantage over explosive damage classes.

For the soldier, they can select the gunboats to decrease self-damage up to 60%, and have greater mobility to get away from the hidden.  Better yet, they could just use the shotgun and have a viable close range weapon in addition to the equalizer/escape plan, right?

**Comment by ghost** [comment]
agreed
