### ISSUE TITLE
Consider Blocking Natasha (or slowing effect)

### ISSUE THREAD

**Issue by ghost** [atomic-penguin/sm-hidden#17]

**Comment by atomic-penguin** [comment]
I don't feel this is game breaking.  Annoying perhaps, if you're the hidden.  It is one thing to be _Marked for Death_ and have a big sign pointing right at the hidden player.  The Mark for Death issue, is as game breking, as if an engineer built a sentry which tracks the hidden's location.

It is another matter to start blocking/nerfing all the weapons that make it unfair for the hidden player.  Where would you stop blocking effects of weapons which are broken in this game mode?
