### ISSUE TITLE
Do we want to change the order in which functions appear in the code?

### ISSUE THREAD

**Issue by ghost** [atomic-penguin/sm-hidden#31]
just a rough grouping, attempting to make it easier to follow the code through by grouping related functions and such.

How it currently is - https://gist.github.com/4462616
Proposed ordering - https://gist.github.com/4462710

**Comment by atomic-penguin** [comment]
I am all for anything that makes the code easier to read.  This may also help later to eliminate redundant functions which could then be combined.

**Comment by ghost** [comment]
ok i will look at re-ordering the code to match the list above, then we can always tweak the order later if we decide it's not quite right

**Comment by ghost** [comment]
https://github.com/atomic-penguin/sm-hidden/pull/32
