### ISSUE TITLE
custom roundtime 1min/60 seconds *probably* not active

### ISSUE THREAD

**Issue by ghost** [atomic-penguin/sm-hidden#40]
possible form of a fix
//OnPluginStart()
new Handle:mp_roundtime = INVALID_HANDLE;
mp_roundtime = FindConVar("mp_roundtime"); 
SetConVarBounds(mp_roundtime, ConVarBound_Upper, true, 1.0);

**Comment by ghost** [comment]
ServerCommand("mp_roundtime 1.0");

**Comment by atomic-penguin** [comment]
Closing this, as we don't want to enforce round time in mod.  The only round length we really care about is the timer on the Hidden's life.  Cleaning up unused code and structures on Issue 4
