### ISSUE TITLE
spectators spawned outside of map

### ISSUE THREAD

**Issue by ghost** [atomic-penguin/sm-hidden#62]
should this call to loop clients

https://github.com/atomic-penguin/sm-hidden/blob/master/scripting/hidden.sp#L961

have the  CLIENTFILTER_NOSPECTATORS flag?

https://github.com/bcserv/smlib/blob/master/scripting/include/smlib/clients.inc#L21

**Comment by atomic-penguin** [comment]
Fixed in v2.11.0
