### ISSUE TITLE
Server game description not correct

### ISSUE THREAD

**Issue by ghost** [atomic-penguin/sm-hidden#7]
Should say something like Hidden TF2, whereas it says Team Fortress 2 as normal

**Comment by ghost** [comment]
this should be a fix! https://github.com/daniel-murray/sm-hidden/commit/ce2181194f5d943784beced38f68ae0f59fd684a

**Comment by ghost** [comment]
1) changed the cvar description to enabled, so we can use enable as an admin cmd suffix.
2) set up the hook for enabling to use the steamtools description method
3) set up a pair of admin cmds to enable and disable

-this shouldn't interfere with anything else as the only place any of this is check is in check enable, which in turn calls PluginStart() where all is untouched.

**Comment by ghost** [comment]
this removes hard coded naming in previous commit in favour of constants defined. https://github.com/daniel-murray/sm-hidden/commit/6aad571298ec6dbb241fd86fca00928b247655e2

**Comment by ghost** [comment]
https://github.com/atomic-penguin/sm-hidden/commit/d5adff00178c91749ed36aafbde94426ee1569e2

**Comment by ghost** [comment]
https://github.com/atomic-penguin/sm-hidden/pull/23

**Comment by atomic-penguin** [comment]
Fixed for sure in commit tagged v2.1.0
