### ISSUE TITLE
Allow the Engy Class - While Preventing the use of Sentries

### ISSUE THREAD

**Issue by ghost** [atomic-penguin/sm-hidden#8]

**Comment by ghost** [comment]
https://gist.github.com/4468745

**Comment by ghost** [comment]
https://github.com/atomic-penguin/sm-hidden/commit/b5347ac79e8a239d6362e30746da9d75612d78f5

**Comment by ghost** [comment]
there is a solution in amongst what we have, i'm just not quite sure what it is yet

**Comment by atomic-penguin** [comment]
You introduced a bug, your build hook destroys sentries on PvP servers even when plugin is inactive.  Need to add a guard check whether the plugin is active, or not.

**Comment by ghost** [comment]
https://github.com/atomic-penguin/sm-hidden/pull/44
